# Generated by Django 3.2.9 on 2021-12-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_example', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
